In [5]:
import numpy as np

In [7]:
# 파이썬 리스틀 통해 생성
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


In [8]:
type(array1)

numpy.ndarray

In [12]:
# 균일한 값으로 생성
array1 = np.full(6, 7)
print(array1)

[7 7 7 7 7 7]


In [34]:
# 모든 값이 0인 numpy array 생성
array1 = np.full(6, 0)
array2 = np.zeros(6, dtype=int)
print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [35]:
# 모든 값이 1인 numpy array 생성
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype=int)
    
print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


In [36]:
# 랜덤한 값들로 생성
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)
    
print(array1)
print()
print(array2)

[0.3120065  0.40372209 0.29620899 0.55170072 0.38162288 0.39952152]

[0.76282336 0.54004999 0.5171189  0.08744759 0.1455063  0.13382622]


In [37]:
# 연속된 값들이 담긴 numpy array 생성
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [38]:
# 파라미터 2개
array1 = numpy.arange(2, 7)
print(array1)

[2 3 4 5 6]


In [39]:
# 파라미터 3개
array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]


In [9]:
import numpy

In [10]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [11]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [16]:
type(array1) # nyarray? : n dimentional arryay : n차원 array

numpy.ndarray

In [17]:
array1.shape # 요소의 개수 확인, 1차원이기 때문에 개수만 알려줌

(11,)

In [22]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [20]:
type(array2)

numpy.ndarray

In [21]:
array2.shape # 행, 열 2차원이기 때문에 3, 4 로 표기

(3, 4)

In [23]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
array1.size # 총 몇개의 요소가 있는지 알려줌

11

In [59]:
array2.size

3

## 인덱싱, 슬라이싱

In [43]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [45]:
array1[[1, 3, 4]] # 리스트 안에 리스트

array([ 3,  7, 11])

In [50]:
array2 = np.array([2, 1, 3])

In [51]:
array1[array2]

array([5, 3, 7])

In [52]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [53]:
array1[0:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [54]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [55]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [58]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

## numpy 기본연산

In [14]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [15]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
for i in range(len(array1)):
    array1[i] = 2 * array1[i]
    # 이런 것들을 간편하기 위해 numpy를 쓰는 것

In [18]:
array1 * 2 # numpy라서 가능한 기능

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [19]:
array1 ** 2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324], dtype=int32)

In [69]:
array1 + array2

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

# numpy 불린 연산

In [3]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [8]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])  

In [9]:
np.where(booleans) #True 값의 위치만 출력

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [10]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [11]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [13]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

# 최댓값, 최솟값

In [14]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max()) # 최댓값
print(array1.min()) # 최솟값

31
5


# 평균값

In [15]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.mean()) # 평균값

15.25


# 중앙값

In [16]:
array1 = np.array([8, 12, 9, 15, 16])
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(np.median(array1)) # 중앙값
print(np.median(array2)) # 중앙값

12.0
13.5


# 표준편차, 분산

In [17]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.std()) # 표준 편차
print(array1.var()) # 분산

8.496322733983215
72.1875
